<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-EMS.EmailReader.Worker-a31c1602-c3d5-43f8-aff7-113196943ff1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EMS.Application\EMS.Application.csproj" />
    <ProjectReference Include="..\EMS.Infrastructure\EMS.Infrastructure.csproj" />
  </ItemGroup>
</Project>
